[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = esp32dev
framework = arduino, espidf
monitor_speed = 115200
board_upload.flash_size = 2MB
board_build.partitions = partitions.csv
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SH110X
